<?php
/*
Plugin Name: Infinity Slider Extension
Plugin URI: http://wordpress.org/plugins/infext-slider/
Description: Infinity Slider is a simple content slider extension for the Infinity Theme Engine.
Author: Marshall Sorenson (MrMaz)
Author URI: http://marshallsorenson.com
License: GNU GENERAL PUBLIC LICENSE 3.0 http://www.gnu.org/licenses/gpl.txt
Version: 1.0
Text Domain: infext-slider
*/

//
// You can override the following constants in
// wp-config.php if you feel the need to.
//
// ***** DO NOT EDIT THIS FILE *****
//

////////////////////////////////
// Important Internal Constants
// *** DO NOT MODIFY THESE ***

// Configuration
define( 'INFEXT_SLIDER_VERSION', '1.0' );
define( 'INFEXT_SLIDER_PLUGIN_BASENAME', plugin_basename( __FILE__ ) );

// Core Paths
define( 'INFEXT_SLIDER_PLUGIN_DIR', dirname( __FILE__ ) );
define( 'INFEXT_SLIDER_PLUGIN_NAME', basename( INFEXT_SLIDER_PLUGIN_DIR ) );
define( 'INFEXT_SLIDER_PLUGIN_URL', WP_PLUGIN_URL . '/' . INFEXT_SLIDER_PLUGIN_NAME );

// Sub Paths
define( 'INFEXT_SLIDER_LIB_DIR', INFEXT_SLIDER_PLUGIN_DIR . '/lib' );
define( 'INFEXT_SLIDER_TPL_DIR', INFEXT_SLIDER_PLUGIN_DIR . '/templates' );
define( 'INFEXT_SLIDER_ASSETS_URL', INFEXT_SLIDER_PLUGIN_URL . '/assets' );
define( 'INFEXT_SLIDER_IMAGES_URL', INFEXT_SLIDER_ASSETS_URL . '/images' );
define( 'INFEXT_SLIDER_CSS_URL', INFEXT_SLIDER_ASSETS_URL . '/css' );
define( 'INFEXT_SLIDER_JS_URL', INFEXT_SLIDER_ASSETS_URL . '/js' );

// ***************************
///////////////////////////////

//
// Plugin Bootstrap Functions
//

/**
 * Configure the slider extension.
 */
function infext_slider_config()
{
	// load extension configuration
	require_once INFEXT_SLIDER_PLUGIN_DIR . '/infext-slider-config.php';

	// post config hook
	do_action( 'infext_slider_config' );
}
add_action( 'infinity_config_loaded', 'infext_slider_config' );

/**
 * Initialize the slider extension.
 */
function infext_slider_init()
{
	// load plugin logic
	require_once INFEXT_SLIDER_PLUGIN_DIR . '/infext-slider-functions.php';
	require_once INFEXT_SLIDER_PLUGIN_DIR . '/infext-slider-setup.php';
	require_once INFEXT_SLIDER_PLUGIN_DIR . '/infext-slider-tags.php';
	
	// in admin?
	if ( true === is_admin() ) {
		// load admin specific logic
		require_once INFEXT_SLIDER_PLUGIN_DIR . '/infext-slider-admin.php';
	}

	// post init hook
	do_action( 'infext_slider_init' );
}
add_action( 'infinity_engine_loaded', 'infext_slider_init' );

/**
 * Handle activation
 *
function infext_slider_activate()
{
	// load upgrade tools
	require_once( 'infext-slider-upgrade.php' );
	// make sure its initialized
	infext_slider_init();
	// run upgrader
	infext_slider_upgrade();
}
add_action( 'activate_' . INFEXT_SLIDER_PLUGIN_BASENAME, 'infext_slider_activate' );
*/